name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create Ready-to-Use Zip
        run: zip -r n8n-nodes-alan.zip package.json dist README.md LICENSE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            n8n-nodes-alan.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}